### ISSUE TITLE
Deal with wildfly-core upgrade to jboss-logging 3.6.x

### ISSUE THREAD

**Issue by simkam** [wildfly-extras/creaper#244]
After [WFCORE-6883](https://issues.redhat.com/browse/WFCORE-6883), wildfly-core was updated to depend on the new `jboss-logging` version, which comes with some new methods. At the same time, Wildly Integration was updated to use those new methods.

Because of that, we started to see many issues like:
```
java.lang.NoSuchMethodError: 'java.lang.Object org.jboss.logging.Logger.getMessageLogger(java.lang.invoke.MethodHandles$Lookup, java.lang.Class, java.lang.String)' at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365) at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273) at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238) at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
```

or
 
```
java.lang.NoSuchMethodError: 'java.lang.Object org.jboss.logging.Logger.getMessageLogger(java.lang.invoke.MethodHandles$Lookup, java.lang.Class, java.lang.String)' at org.jboss.as.protocol.logging.ProtocolLogger.<clinit>(ProtocolLogger.java:37) at org.jboss.as.protocol.mgmt.AbstractMessageHandler.registerActiveOperation(AbstractMessageHandler.java:387) at org.jboss.as.protocol.mgmt.AbstractMessageHandler.registerActiveOperation(AbstractMessageHandler.java:336) at org.jboss.as.protocol.mgmt.ManagementChannelHandler.executeRequest(ManagementChannelHandler.java:92) at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeRequest(AbstractModelControllerClient.java:249) at org.jboss.as.controller.client.impl.AbstractModelControllerClient.execute(AbstractModelControllerClient.java:154) at org.jboss.as.controller.client.impl.AbstractModelControllerClient.executeForResult(AbstractModelControllerClient.java:133) at org.jboss.as.controller.client.impl.AbstractModelControllerClient.execute(AbstractModelControllerClient.java:61) at org.wildfly.extras.creaper.core.online.OnlineOptions.connectAndWaitUntilServerBoots(OnlineOptions.java:449) at org.wildfly.extras.creaper.core.online.OnlineOptions.createModelControllerClient(OnlineOptions.java:423) at org.wildfly.extras.creaper.core.online.OnlineManagementClientImpl.connect(OnlineManagementClientImpl.java:42) at org.wildfly.extras.creaper.core.online.OnlineManagementClientImpl.<init>(OnlineManagementClientImpl.java:38) at org.wildfly.extras.creaper.core.online.OnlineOptions$2.create(OnlineOptions.java:493) at org.wildfly.extras.creaper.core.ManagementClient.online(ManagementClient.java:36)
```

From quick investigation, it seems the problem might be that the version of `jboss-logging` in the dependency tree is lower than 3.6.0 (and thus missing the new method)—IOW, we have a dependency on recent enough `wildfly-core` / `wildfly-cli` that tries to use that new method.
`wildfly-core` / `wildfly-cli` depends on new `jboss-logging` so that is not a problem but some other artifact's transitive `jboss-logging` (older) is resolved by maven.

So far, the only viable solution we have come up with is updating all test suites and tooling projects to depend on the latest `jboss-logging` 3.6.x. We hope we will not have to change that for another ten years like was the case with previous versions.

Alternatively we could remove explicit dependency on `jboss-logging` and allow it to be transitive (through WildFly Core ideally). 

There is one change though - `jboss-logging` 3.6.x is JDK11+ only which isn't the problem for EAP 8.x testsuites but might be for some tooling projects (like Creaper) so we need to deal with that too.

**Comment by mchoma** [comment]
@dosu are you already here?
