### ISSUE TITLE
The test AddUndertowListenerOnlineTest.addHttpsConnector_commandSucceeds fails on WildFly 10.0.0.CR5

### ISSUE THREAD

**Issue by Ladicek** [wildfly-extras/creaper#45]
When moving to WildFly 10.0.0.CR5 (see commit https://github.com/Ladicek/creaper/commit/87c25e7898), the test `AddUndertowListenerOnlineTest.addHttpsConnector_commandSucceeds` starts failing with this error:

```
09:14:31,186 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.undertow.listener.test-listener: org.jboss.msc.service.StartException in service jboss.undertow.listener.test-listener: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: WFLYUT0079: No SSL Context available from security realm. Either the realm is not configured for SSL, or the server has not been reloaded since the SSL config was added.
	at org.wildfly.extension.undertow.HttpsListenerService.startListening(HttpsListenerService.java:117)
	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:138)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	... 3 more

09:14:31,195 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 2) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "undertow"),
    ("server" => "default-server"),
    ("https-listener" => "test-listener")
]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.listener.test-listener" => "org.jboss.msc.service.StartException in service jboss.undertow.listener.test-listener: Failed to start service
    Caused by: java.lang.IllegalStateException: WFLYUT0079: No SSL Context available from security realm. Either the realm is not configured for SSL, or the server has not been reloaded since the SSL config was added."}}
```

Run this command to observe the problem (using Java 8): `mvn clean test -Dtest=AddUndertowListenerOnlineTest#addHttpsConnector_commandSucceeds -DfailIfNoTests=false`

The purpose of this issue is investigation: is it a problem in the test, or did we find a problem in WildFly? (My guess is that it's a problem with the test, there really is no SSL configuration in `ApplicationRealm`, but I'm far from an expert on this.)

**Comment by Ladicek** [comment]
Not sure why the test passes with WildFly 10.0.0.CR4 -- maybe they fixed a bug?

**Comment by rhatlapa** [comment]
I will look at it.

**Comment by Ladicek** [comment]
I was able to fix the test by https://github.com/Ladicek/creaper/commit/d7d4913c7d, but the question remains: is it a test problem, or a WildFly problem?

**Comment by rhatlapa** [comment]
Nice fix, you can add it to master as it is really a test problem as there was added improved check that used realm is for ssl => providing ssl context

**Comment by Ladicek** [comment]
Thanks. Reassigning to myself, as I have the fix ready.
